In [1]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize


data = pd.read_csv("../data/fd_dataset_messy.csv")
print(data.head(5))

                         email                 time        subject  \
0  mukesh.bhatt@rediffmail.com  2025-02-17 20:29:47  Payment issue
1      sanjay.jain@hotmail.com  2024-06-07 16:22:21           Help
2         ashok.nair@gmail.com  2024-04-05 08:16:39     Loan query
3    manoj.gupta51@hotmail.com  2025-01-04 23:24:05          Query
4     vinod.chopra87@gmail.com  2025-03-03 10:12:43    Loan status

                                             content              label
0  Branch gaya tha, unhone email karne bola. Two ...             Non-FD
1  Dear customer care, My insurance policy is rea...             Non-FD
2  Namaskar, Rs 6 lakh kat gaya bina bataye insur...             Non-FD
3  Dear customer care, 1. Suna hai Bajaj Finance ...  Multiple Category
4  Dear customer care, Where is my money? The rev...             Non-FD

In [2]:
# lowercase right after reading
data['content'] = data['content'].str.lower()
data['subject'] = data['subject'].str.lower()

data.head(5)

,email,time,subject,content,label
0,mukesh.bhatt@rediffmail.com,2025-02-17 20:29:47,payment issue,"branch gaya tha, unhone email karne bola. two ...",Non-FD
1,sanjay.jain@hotmail.com,2024-06-07 16:22:21,help,"dear customer care, my insurance policy is rea...",Non-FD
2,ashok.nair@gmail.com,2024-04-05 08:16:39,loan query,"namaskar, rs 6 lakh kat gaya bina bataye insur...",Non-FD
3,manoj.gupta51@hotmail.com,2025-01-04 23:24:05,query,"dear customer care, 1. suna hai bajaj finance ...",Multiple Category
4,vinod.chopra87@gmail.com,2025-03-03 10:12:43,loan status,"dear customer care, where is my money? the rev...",Non-FD

##### Word Tokenizer

In [ ]:
content_token = []

for text in data['content']:
    tokens = word_tokenize(str(text))
    content_token.append(tokens)

data['content_token'] = content_token
print("First Email Content:", data['content'][0])
print("\n")
print("First Email Content Tokens:", content_token[0])

First Email Content: branch gaya tha, unhone email karne bola. two wheeler loan ki emi is mahine zyada kati hai. pehle se rs 800 jyada. kyu? statement bhejo. bahut pareshan ho gaya hoon. mukesh bhatt
First Email Content Tokens: ['branch', 'gaya', 'tha', ',', 'unhone', 'email', 'karne', 'bola', '.', 'two', 'wheeler', 'loan', 'ki', 'emi', 'is', 'mahine', 'zyada', 'kati', 'hai', '.', 'pehle', 'se', 'rs', '800', 'jyada', '.', 'kyu', '?', 'statement', 'bhejo', '.', 'bahut', 'pareshan', 'ho', 'gaya', 'hoon', '.', 'mukesh', 'bhatt']

In [4]:
print(data.head(5))

                         email                 time        subject  \
0  mukesh.bhatt@rediffmail.com  2025-02-17 20:29:47  payment issue
1      sanjay.jain@hotmail.com  2024-06-07 16:22:21           help
2         ashok.nair@gmail.com  2024-04-05 08:16:39     loan query
3    manoj.gupta51@hotmail.com  2025-01-04 23:24:05          query
4     vinod.chopra87@gmail.com  2025-03-03 10:12:43    loan status

                                             content              label  \
0  branch gaya tha, unhone email karne bola. two ...             Non-FD
1  dear customer care, my insurance policy is rea...             Non-FD
2  namaskar, rs 6 lakh kat gaya bina bataye insur...             Non-FD
3  dear customer care, 1. suna hai bajaj finance ...  Multiple Category
4  dear customer care, where is my money? the rev...             Non-FD

                                       content_token
0  [branch, gaya, tha, ,, unhone, email, karne, b...
1  [dear, customer, care, ,, my, insurance, polic...
2  [namaskar, ,, rs, 6, lakh, kat, gaya, bina, ba...
3  [dear, customer, care, ,, 1., suna, hai, bajaj...
4  [dear, customer, care, ,, where, is, my, money...

##### Character Tokenizer

In [ ]:
ch_token = []

for text in data['content']:
    tokens  =[]
    for ch in str(text):
        if ch.isalpha():    # ch.isalpha() is True (skipping spaces, punctuation, digits, etc.).
            tokens.append(ch)
    ch_token.append(tokens)

print("First Email Content:", data['content'][0])
print("First Email Alpha-Only Char Tokens:", ch_token[0])
print("\n")
data['content_char_token'] = ch_token

First Email Content: branch gaya tha, unhone email karne bola. two wheeler loan ki emi is mahine zyada kati hai. pehle se rs 800 jyada. kyu? statement bhejo. bahut pareshan ho gaya hoon. mukesh bhatt
First Email Alpha-Only Char Tokens: ['b', 'r', 'a', 'n', 'c', 'h', 'g', 'a', 'y', 'a', 't', 'h', 'a', 'u', 'n', 'h', 'o', 'n', 'e', 'e', 'm', 'a', 'i', 'l', 'k', 'a', 'r', 'n', 'e', 'b', 'o', 'l', 'a', 't', 'w', 'o', 'w', 'h', 'e', 'e', 'l', 'e', 'r', 'l', 'o', 'a', 'n', 'k', 'i', 'e', 'm', 'i', 'i', 's', 'm', 'a', 'h', 'i', 'n', 'e', 'z', 'y', 'a', 'd', 'a', 'k', 'a', 't', 'i', 'h', 'a', 'i', 'p', 'e', 'h', 'l', 'e', 's', 'e', 'r', 's', 'j', 'y', 'a', 'd', 'a', 'k', 'y', 'u', 's', 't', 'a', 't', 'e', 'm', 'e', 'n', 't', 'b', 'h', 'e', 'j', 'o', 'b', 'a', 'h', 'u', 't', 'p', 'a', 'r', 'e', 's', 'h', 'a', 'n', 'h', 'o', 'g', 'a', 'y', 'a', 'h', 'o', 'o', 'n', 'm', 'u', 'k', 'e', 's', 'h', 'b', 'h', 'a', 't', 't']

In [6]:
data.head(5)

,email,time,subject,content,label,content_token,content_char_token
0,mukesh.bhatt@rediffmail.com,2025-02-17 20:29:47,payment issue,"branch gaya tha, unhone email karne bola. two ...",Non-FD,"[branch, gaya, tha, ,, unhone, email, karne, b...","[b, r, a, n, c, h, g, a, y, a, t, h, a, u, n, ..."
1,sanjay.jain@hotmail.com,2024-06-07 16:22:21,help,"dear customer care, my insurance policy is rea...",Non-FD,"[dear, customer, care, ,, my, insurance, polic...","[d, e, a, r, c, u, s, t, o, m, e, r, c, a, r, ..."
2,ashok.nair@gmail.com,2024-04-05 08:16:39,loan query,"namaskar, rs 6 lakh kat gaya bina bataye insur...",Non-FD,"[namaskar, ,, rs, 6, lakh, kat, gaya, bina, ba...","[n, a, m, a, s, k, a, r, r, s, l, a, k, h, k, ..."
3,manoj.gupta51@hotmail.com,2025-01-04 23:24:05,query,"dear customer care, 1. suna hai bajaj finance ...",Multiple Category,"[dear, customer, care, ,, 1., suna, hai, bajaj...","[d, e, a, r, c, u, s, t, o, m, e, r, c, a, r, ..."
4,vinod.chopra87@gmail.com,2025-03-03 10:12:43,loan status,"dear customer care, where is my money? the rev...",Non-FD,"[dear, customer, care, ,, where, is, my, money...","[d, e, a, r, c, u, s, t, o, m, e, r, c, a, r, ..."

##### BPE Tokenizer used in GPT

Important Points
- BPE(unk_token="[UNK]") 
    - This creates the actual algorithm (the BPE model) that will learn and apply merge rules. 
    - The unk_token="[UNK]" part tells it: "if you ever see a token during tokenization that wasn't learned in training, replace it with this placeholder instead of crashing." 
    - UNK = unknown.

- Whitespace()
    - Before BPE can merge characters into subwords, it needs initial word boundaries — otherwise it might try merging characters across two different words. 
    - Whitespace() splits text on spaces and separates punctuation into its own piece. 

- train_from_iterator
    - This is where the real BPE algorithm runs, following exactly the flow from your cheatsheet:
    1. Starts by breaking every pre-tokenized chunk into individual characters ("branch" → b,r,a,n,c,h).
    2. Scans your whole data['content'] column and counts which adjacent character pairs occur most often.
    3. Repeatedly merges the most frequent pair into a single new subword, then recounts, then merges again.
    4. Stops once the vocabulary reaches vocab_size=1000 total subwords.
    5. special_tokens=["[UNK]"] reserves a slot in that vocabulary specifically for [UNK] — without this, the earlier error you saw (Unk token not found) happens, since [UNK] wouldn't exist in the learned vocabulary at all.

In [ ]:
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import Whitespace

bpe_tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
bpe_tokenizer.pre_tokenizer = Whitespace()
bpe_tokenizer.train_from_iterator(data['content'], BpeTrainer(vocab_size=1000, special_tokens=["[UNK]"]))

bpe_token = []
for text in data['content']:
    tokens = bpe_tokenizer.encode(str(text)).tokens
    bpe_token.append(tokens)

data['bpe_token'] = bpe_token
print("First Email Content:", data['content'][0])
print("\n")
print("First Email BPE Tokens:", bpe_token[0])

First Email Content: branch gaya tha, unhone email karne bola. two wheeler loan ki emi is mahine zyada kati hai. pehle se rs 800 jyada. kyu? statement bhejo. bahut pareshan ho gaya hoon. mukesh bhatt
First Email BPE Tokens: ['branch', 'gaya', 'tha', ',', 'unhone', 'email', 'karne', 'bola', '.', 'two', 'whe', 'el', 'er', 'loan', 'ki', 'emi', 'is', 'mahine', 'zyada', 'k', 'ati', 'hai', '.', 'pehle', 'se', 'rs', '8', '00', 'j', 'yada', '.', 'ky', 'u', '?', 'statement', 'bhe', 'jo', '.', 'bahut', 'pareshan', 'ho', 'gaya', 'hoon', '.', 'mukesh', 'bhatt']

##### Word Piece Tokenizer used in BERT

In [ ]:
from tokenizers import Tokenizer
from tokenizers.models import WordPiece
from tokenizers.trainers import WordPieceTrainer
from tokenizers.pre_tokenizers import Whitespace

wp_tokenizer = Tokenizer(WordPiece(unk_token="[UNK]"))
wp_tokenizer.pre_tokenizer = Whitespace()
wp_tokenizer.train_from_iterator(data['content'], WordPieceTrainer(vocab_size=1000, special_tokens=["[UNK]"]))

wordpiece_token = []
for text in data['content']:
    tokens = wp_tokenizer.encode(str(text)).tokens
    wordpiece_token.append(tokens)

data['wordpiece_token'] = wordpiece_token
print("First Email Content:", data['content'][0])
print("\n")
print("First Email WordPiece Tokens:", wordpiece_token[0])

First Email Content: branch gaya tha, unhone email karne bola. two wheeler loan ki emi is mahine zyada kati hai. pehle se rs 800 jyada. kyu? statement bhejo. bahut pareshan ho gaya hoon. mukesh bhatt
First Email WordPiece Tokens: ['branch', 'gaya', 'tha', ',', 'unhone', 'email', 'karne', 'bola', '.', 'two', 'wh', '##ee', '##le', '##r', 'loan', 'ki', 'emi', 'is', 'mahine', 'zyada', 'kat', '##i', 'hai', '.', 'pehle', 'se', 'rs', '8', '##00', 'j', '##yada', '.', 'ky', '##u', '?', 'statement', 'bh', '##e', '##j', '##o', '.', 'bahut', 'pareshan', 'ho', 'gaya', 'hoon', '.', 'mukesh', 'bhatt']

##### Sentence Piece Tokenizer

Important Points

- model_prefix="sp_model" 
    - This is the important part. Unlike the HuggingFace tokenizers library (which keeps the trained tokenizer as a Python object in memory, e.g. bpe_tokenizer), SentencePiece writes the trained model straight to disk as two files: sp_model.model and sp_model.vocab.

- sp = spm.SentencePieceProcessor() and sp.load("sp_model.model")
    - This is the step that's easy to miss the purpose of: spm.SentencePieceTrainer.train(...) only creates the files — it doesn't hand you back a ready-to-use tokenizer object. 
    - So you create a fresh, empty SentencePieceProcessor(), then .load("sp_model.model") reads the trained model file back off disk into that object.

In [10]:
import sentencepiece as spm

spm.SentencePieceTrainer.train(
    sentence_iterator=iter(data['content']),
    model_prefix="sp_model",
    vocab_size=1000,
    model_type="bpe"
)

sp = spm.SentencePieceProcessor()
sp.load("sp_model.model")

sentencepiece_token = []
for text in data['content']:
    tokens = sp.encode(str(text), out_type=str)
    sentencepiece_token.append(tokens)

data['sentencepiece_token'] = sentencepiece_token
print("First Email Content:", data['content'][0])
print("\n")
print("First Email SentencePiece Tokens:", sentencepiece_token[0])

First Email Content: branch gaya tha, unhone email karne bola. two wheeler loan ki emi is mahine zyada kati hai. pehle se rs 800 jyada. kyu? statement bhejo. bahut pareshan ho gaya hoon. mukesh bhatt


First Email SentencePiece Tokens: ['▁branch', '▁gaya', '▁tha', ',', '▁unhone', '▁email', '▁karne', '▁bola', '.', '▁two', '▁whe', 'e', 'l', 'er', '▁loan', '▁ki', '▁emi', '▁is', '▁mahine', '▁zyada', '▁k', 'ati', '▁hai', '.', '▁pehle', '▁se', '▁rs', '▁', '8', '00', '▁j', 'yada', '.', '▁ky', 'u', '?', '▁statement', '▁b', 'he', 'j', 'o', '.', '▁bahut', '▁pareshan', '▁ho', '▁gaya', '▁hoon', '.', '▁mukesh', '▁bhatt']